config/routes.rb
Roktok2::Application.routes.draw do
  resources :archives

  root :to => 'archives#index'

end

app/models/archive.rb
class Archive < ActiveRecord::Base
  validates_uniqueness_of :archiveID
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  # GET /archives
  # GET /archives.json
  def index
    @archives = Archive.all
    
    @archiveID = params[:archiveID];
    if(@archiveID.nil? == false) 
       @archive = Archive.new(:archiveID =>@archiveID)
       respond_to do |format|
         if @archive.save
           format.html { redirect_to @archive, notice: 'Archive was successfully created.' }
           format.json { render json: @archive, status: :created, location: @archive }
         else
           format.html { render action: "new" }
           format.json { render json: @archive.errors, status: :unprocessable_entity }
         end
       end
   else
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @archives }
    end
  end
  end

  # GET /archives/1
  # GET /archives/1.json
  def show
    @archive = Archive.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @archive }
    end
  end
  
   # GET /archives/last.json
   def show
     @archive = Archive.find(:last)

     respond_to do |format|
       format.json { render json: @archive }
     end
   end

  # GET /archives/new
  # GET /archives/new.json
  def new
    @archive = Archive.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @archive }
    end
  end

  # GET /archives/1/edit
  def edit
    @archive = Archive.find(params[:id])
  end

  # POST /archives
  # POST /archives.json
  def create
    @archive = Archive.new(params[:archive])

    respond_to do |format|
      if @archive.save
        format.html { redirect_to @archive, notice: 'Archive was successfully created.' }
        format.json { render json: @archive, status: :created, location: @archive }
      else
        format.html { render action: "new" }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /archives/1
  # PUT /archives/1.json
  def update
    @archive = Archive.find(params[:id])

    respond_to do |format|
      if @archive.update_attributes(params[:archive])
        format.html { redirect_to @archive, notice: 'Archive was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.json
  def destroy
    @archive = Archive.find(params[:id])
    @archive.destroy

    respond_to do |format|
      format.html { redirect_to archives_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/views/archives/_form.html.erb
<%= form_for(@archive) do |f| %>
  <% if @archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

      <ul>
      <% @archive.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :archiveID %><br />
    <%= f.text_field :archiveID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/archives/edit.html.erb
<h1>Editing archive</h1>

<%= render 'form' %>

<%= link_to 'Show', @archive %> |
<%= link_to 'Back', archives_path %>

app/views/archives/index.html.erb
<h1>Listing archives</h1>

<table>
  <tr>
    <th>Archiveid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @archives.each do |archive| %>
  <tr>
    <td><%= archive.archiveID %></td>
    <td><%= link_to 'Show', archive %></td>
    <td><%= link_to 'Edit', edit_archive_path(archive) %></td>
    <td><%= link_to 'Destroy', archive, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Archive', new_archive_path %>

app/views/archives/new.html.erb
<h1>New archive</h1>

<%= render 'form' %>

<%= link_to 'Back', archives_path %>

app/views/archives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Archiveid:</b>
  <%= @archive.archiveID %>
</p>


<%= link_to 'Edit', edit_archive_path(@archive) %> |
<%= link_to 'Back', archives_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roktok2</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>